// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LoginPlatform int32                  `protobuf:"varint,3,opt,name=loginPlatform,proto3" json:"loginPlatform,omitempty"`
	SmsCode       string                 `protobuf:"bytes,4,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterParams) Reset() {
	*x = RegisterParams{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterParams) ProtoMessage() {}

func (x *RegisterParams) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterParams.ProtoReflect.Descriptor instead.
func (*RegisterParams) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterParams) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterParams) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterParams) GetLoginPlatform() int32 {
	if x != nil {
		return x.LoginPlatform
	}
	return 0
}

func (x *RegisterParams) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserParams) Reset() {
	*x = UserParams{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserParams) ProtoMessage() {}

func (x *UserParams) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserParams.ProtoReflect.Descriptor instead.
func (*UserParams) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserParams) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserDTO struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uid              string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname         string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar           string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AvatarFrame      string                 `protobuf:"bytes,4,opt,name=avatarFrame,proto3" json:"avatarFrame,omitempty"`
	Sex              int32                  `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Gold             int64                  `protobuf:"varint,6,opt,name=gold,proto3" json:"gold,omitempty"`
	EmailArr         string                 `protobuf:"bytes,7,opt,name=emailArr,proto3" json:"emailArr,omitempty"`
	MobilePhone      string                 `protobuf:"bytes,8,opt,name=mobilePhone,proto3" json:"mobilePhone,omitempty"`
	RealName         string                 `protobuf:"bytes,9,opt,name=realName,proto3" json:"realName,omitempty"`
	IsAgent          bool                   `protobuf:"varint,10,opt,name=isAgent,proto3" json:"isAgent,omitempty"`
	RoomID           string                 `protobuf:"bytes,11,opt,name=roomID,proto3" json:"roomID,omitempty"`
	FrontendId       string                 `protobuf:"bytes,12,opt,name=frontendId,proto3" json:"frontendId,omitempty"`
	Address          string                 `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	Location         string                 `protobuf:"bytes,14,opt,name=location,proto3" json:"location,omitempty"`
	IsBlockedAccount int32                  `protobuf:"varint,15,opt,name=isBlockedAccount,proto3" json:"isBlockedAccount,omitempty"`
	LastLoginIP      string                 `protobuf:"bytes,16,opt,name=lastLoginIP,proto3" json:"lastLoginIP,omitempty"`
	LastLoginTime    int64                  `protobuf:"varint,17,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	CreateTime       int64                  `protobuf:"varint,18,opt,name=createTime,proto3" json:"createTime,omitempty"`
	InviteMsg        []*InviteMsg           `protobuf:"bytes,19,rep,name=inviteMsg,proto3" json:"inviteMsg,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserDTO) Reset() {
	*x = UserDTO{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDTO) ProtoMessage() {}

func (x *UserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDTO.ProtoReflect.Descriptor instead.
func (*UserDTO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDTO) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserDTO) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDTO) GetAvatarFrame() string {
	if x != nil {
		return x.AvatarFrame
	}
	return ""
}

func (x *UserDTO) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserDTO) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UserDTO) GetEmailArr() string {
	if x != nil {
		return x.EmailArr
	}
	return ""
}

func (x *UserDTO) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *UserDTO) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserDTO) GetIsAgent() bool {
	if x != nil {
		return x.IsAgent
	}
	return false
}

func (x *UserDTO) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *UserDTO) GetFrontendId() string {
	if x != nil {
		return x.FrontendId
	}
	return ""
}

func (x *UserDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserDTO) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserDTO) GetIsBlockedAccount() int32 {
	if x != nil {
		return x.IsBlockedAccount
	}
	return 0
}

func (x *UserDTO) GetLastLoginIP() string {
	if x != nil {
		return x.LastLoginIP
	}
	return ""
}

func (x *UserDTO) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *UserDTO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserDTO) GetInviteMsg() []*InviteMsg {
	if x != nil {
		return x.InviteMsg
	}
	return nil
}

type InviteMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UnionID       int64                  `protobuf:"varint,3,opt,name=unionID,proto3" json:"unionID,omitempty"`
	Partner       bool                   `protobuf:"varint,4,opt,name=partner,proto3" json:"partner,omitempty"`
	UnionName     string                 `protobuf:"bytes,5,opt,name=unionName,proto3" json:"unionName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMsg) Reset() {
	*x = InviteMsg{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMsg) ProtoMessage() {}

func (x *InviteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMsg.ProtoReflect.Descriptor instead.
func (*InviteMsg) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *InviteMsg) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InviteMsg) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InviteMsg) GetUnionID() int64 {
	if x != nil {
		return x.UnionID
	}
	return 0
}

func (x *InviteMsg) GetPartner() bool {
	if x != nil {
		return x.Partner
	}
	return false
}

func (x *InviteMsg) GetUnionName() string {
	if x != nil {
		return x.UnionName
	}
	return ""
}

type UnionInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InviteID                  int64                  `protobuf:"varint,1,opt,name=inviteID,proto3" json:"inviteID,omitempty"`
	UnionID                   int64                  `protobuf:"varint,2,opt,name=unionID,proto3" json:"unionID,omitempty"`
	SpreaderID                string                 `protobuf:"bytes,3,opt,name=spreaderID,proto3" json:"spreaderID,omitempty"`
	Score                     int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	SafeScore                 int64                  `protobuf:"varint,5,opt,name=safeScore,proto3" json:"safeScore,omitempty"`
	Partner                   bool                   `protobuf:"varint,6,opt,name=partner,proto3" json:"partner,omitempty"`
	RebateRate                int64                  `protobuf:"varint,7,opt,name=rebateRate,proto3" json:"rebateRate,omitempty"`
	TodayDraw                 int64                  `protobuf:"varint,8,opt,name=todayDraw,proto3" json:"todayDraw,omitempty"`
	YesterdayDraw             int64                  `protobuf:"varint,9,opt,name=yesterdayDraw,proto3" json:"yesterdayDraw,omitempty"`
	TotalDraw                 int64                  `protobuf:"varint,10,opt,name=totalDraw,proto3" json:"totalDraw,omitempty"`
	WeekDraw                  int64                  `protobuf:"varint,11,opt,name=weekDraw,proto3" json:"weekDraw,omitempty"`
	MemberTodayDraw           int64                  `protobuf:"varint,12,opt,name=memberTodayDraw,proto3" json:"memberTodayDraw,omitempty"`
	MemberYesterdayDraw       int64                  `protobuf:"varint,13,opt,name=memberYesterdayDraw,proto3" json:"memberYesterdayDraw,omitempty"`
	TodayBigWinDraw           int64                  `protobuf:"varint,14,opt,name=todayBigWinDraw,proto3" json:"todayBigWinDraw,omitempty"`
	YesterdayBigWinDraw       int64                  `protobuf:"varint,15,opt,name=yesterdayBigWinDraw,proto3" json:"yesterdayBigWinDraw,omitempty"`
	MemberTodayBigWinDraw     int64                  `protobuf:"varint,16,opt,name=memberTodayBigWinDraw,proto3" json:"memberTodayBigWinDraw,omitempty"`
	MemberYesterdayBigWinDraw int64                  `protobuf:"varint,17,opt,name=memberYesterdayBigWinDraw,proto3" json:"memberYesterdayBigWinDraw,omitempty"`
	TodayProvideRebate        int64                  `protobuf:"varint,18,opt,name=todayProvideRebate,proto3" json:"todayProvideRebate,omitempty"`
	YesterdayProvideRebate    int64                  `protobuf:"varint,19,opt,name=yesterdayProvideRebate,proto3" json:"yesterdayProvideRebate,omitempty"`
	TodayRebate               int64                  `protobuf:"varint,20,opt,name=todayRebate,proto3" json:"todayRebate,omitempty"`
	YesterdayRebate           int64                  `protobuf:"varint,21,opt,name=yesterdayRebate,proto3" json:"yesterdayRebate,omitempty"`
	TotalRebate               int64                  `protobuf:"varint,22,opt,name=totalRebate,proto3" json:"totalRebate,omitempty"`
	TodayWin                  int64                  `protobuf:"varint,23,opt,name=todayWin,proto3" json:"todayWin,omitempty"`
	YesterdayWin              int64                  `protobuf:"varint,24,opt,name=yesterdayWin,proto3" json:"yesterdayWin,omitempty"`
	ProhibitGame              int64                  `protobuf:"varint,25,opt,name=prohibitGame,proto3" json:"prohibitGame,omitempty"`
	JoinTime                  int64                  `protobuf:"varint,26,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UnionInfo) Reset() {
	*x = UnionInfo{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionInfo) ProtoMessage() {}

func (x *UnionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionInfo.ProtoReflect.Descriptor instead.
func (*UnionInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UnionInfo) GetInviteID() int64 {
	if x != nil {
		return x.InviteID
	}
	return 0
}

func (x *UnionInfo) GetUnionID() int64 {
	if x != nil {
		return x.UnionID
	}
	return 0
}

func (x *UnionInfo) GetSpreaderID() string {
	if x != nil {
		return x.SpreaderID
	}
	return ""
}

func (x *UnionInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UnionInfo) GetSafeScore() int64 {
	if x != nil {
		return x.SafeScore
	}
	return 0
}

func (x *UnionInfo) GetPartner() bool {
	if x != nil {
		return x.Partner
	}
	return false
}

func (x *UnionInfo) GetRebateRate() int64 {
	if x != nil {
		return x.RebateRate
	}
	return 0
}

func (x *UnionInfo) GetTodayDraw() int64 {
	if x != nil {
		return x.TodayDraw
	}
	return 0
}

func (x *UnionInfo) GetYesterdayDraw() int64 {
	if x != nil {
		return x.YesterdayDraw
	}
	return 0
}

func (x *UnionInfo) GetTotalDraw() int64 {
	if x != nil {
		return x.TotalDraw
	}
	return 0
}

func (x *UnionInfo) GetWeekDraw() int64 {
	if x != nil {
		return x.WeekDraw
	}
	return 0
}

func (x *UnionInfo) GetMemberTodayDraw() int64 {
	if x != nil {
		return x.MemberTodayDraw
	}
	return 0
}

func (x *UnionInfo) GetMemberYesterdayDraw() int64 {
	if x != nil {
		return x.MemberYesterdayDraw
	}
	return 0
}

func (x *UnionInfo) GetTodayBigWinDraw() int64 {
	if x != nil {
		return x.TodayBigWinDraw
	}
	return 0
}

func (x *UnionInfo) GetYesterdayBigWinDraw() int64 {
	if x != nil {
		return x.YesterdayBigWinDraw
	}
	return 0
}

func (x *UnionInfo) GetMemberTodayBigWinDraw() int64 {
	if x != nil {
		return x.MemberTodayBigWinDraw
	}
	return 0
}

func (x *UnionInfo) GetMemberYesterdayBigWinDraw() int64 {
	if x != nil {
		return x.MemberYesterdayBigWinDraw
	}
	return 0
}

func (x *UnionInfo) GetTodayProvideRebate() int64 {
	if x != nil {
		return x.TodayProvideRebate
	}
	return 0
}

func (x *UnionInfo) GetYesterdayProvideRebate() int64 {
	if x != nil {
		return x.YesterdayProvideRebate
	}
	return 0
}

func (x *UnionInfo) GetTodayRebate() int64 {
	if x != nil {
		return x.TodayRebate
	}
	return 0
}

func (x *UnionInfo) GetYesterdayRebate() int64 {
	if x != nil {
		return x.YesterdayRebate
	}
	return 0
}

func (x *UnionInfo) GetTotalRebate() int64 {
	if x != nil {
		return x.TotalRebate
	}
	return 0
}

func (x *UnionInfo) GetTodayWin() int64 {
	if x != nil {
		return x.TodayWin
	}
	return 0
}

func (x *UnionInfo) GetYesterdayWin() int64 {
	if x != nil {
		return x.YesterdayWin
	}
	return 0
}

func (x *UnionInfo) GetProhibitGame() int64 {
	if x != nil {
		return x.ProhibitGame
	}
	return 0
}

func (x *UnionInfo) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"\x86\x01\n" +
	"\x0eRegisterParams\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12$\n" +
	"\rloginPlatform\x18\x03 \x01(\x05R\rloginPlatform\x12\x18\n" +
	"\asmsCode\x18\x04 \x01(\tR\asmsCode\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\x1e\n" +
	"\n" +
	"UserParams\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\xb7\x04\n" +
	"\aUserDTO\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vavatarFrame\x18\x04 \x01(\tR\vavatarFrame\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\x05R\x03sex\x12\x12\n" +
	"\x04gold\x18\x06 \x01(\x03R\x04gold\x12\x1a\n" +
	"\bemailArr\x18\a \x01(\tR\bemailArr\x12 \n" +
	"\vmobilePhone\x18\b \x01(\tR\vmobilePhone\x12\x1a\n" +
	"\brealName\x18\t \x01(\tR\brealName\x12\x18\n" +
	"\aisAgent\x18\n" +
	" \x01(\bR\aisAgent\x12\x16\n" +
	"\x06roomID\x18\v \x01(\tR\x06roomID\x12\x1e\n" +
	"\n" +
	"frontendId\x18\f \x01(\tR\n" +
	"frontendId\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12\x1a\n" +
	"\blocation\x18\x0e \x01(\tR\blocation\x12*\n" +
	"\x10isBlockedAccount\x18\x0f \x01(\x05R\x10isBlockedAccount\x12 \n" +
	"\vlastLoginIP\x18\x10 \x01(\tR\vlastLoginIP\x12$\n" +
	"\rlastLoginTime\x18\x11 \x01(\x03R\rlastLoginTime\x12\x1e\n" +
	"\n" +
	"createTime\x18\x12 \x01(\x03R\n" +
	"createTime\x12(\n" +
	"\tinviteMsg\x18\x13 \x03(\v2\n" +
	".InviteMsgR\tinviteMsg\"\x8b\x01\n" +
	"\tInviteMsg\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\aunionID\x18\x03 \x01(\x03R\aunionID\x12\x18\n" +
	"\apartner\x18\x04 \x01(\bR\apartner\x12\x1c\n" +
	"\tunionName\x18\x05 \x01(\tR\tunionName\"\xcf\a\n" +
	"\tUnionInfo\x12\x1a\n" +
	"\binviteID\x18\x01 \x01(\x03R\binviteID\x12\x18\n" +
	"\aunionID\x18\x02 \x01(\x03R\aunionID\x12\x1e\n" +
	"\n" +
	"spreaderID\x18\x03 \x01(\tR\n" +
	"spreaderID\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x1c\n" +
	"\tsafeScore\x18\x05 \x01(\x03R\tsafeScore\x12\x18\n" +
	"\apartner\x18\x06 \x01(\bR\apartner\x12\x1e\n" +
	"\n" +
	"rebateRate\x18\a \x01(\x03R\n" +
	"rebateRate\x12\x1c\n" +
	"\ttodayDraw\x18\b \x01(\x03R\ttodayDraw\x12$\n" +
	"\ryesterdayDraw\x18\t \x01(\x03R\ryesterdayDraw\x12\x1c\n" +
	"\ttotalDraw\x18\n" +
	" \x01(\x03R\ttotalDraw\x12\x1a\n" +
	"\bweekDraw\x18\v \x01(\x03R\bweekDraw\x12(\n" +
	"\x0fmemberTodayDraw\x18\f \x01(\x03R\x0fmemberTodayDraw\x120\n" +
	"\x13memberYesterdayDraw\x18\r \x01(\x03R\x13memberYesterdayDraw\x12(\n" +
	"\x0ftodayBigWinDraw\x18\x0e \x01(\x03R\x0ftodayBigWinDraw\x120\n" +
	"\x13yesterdayBigWinDraw\x18\x0f \x01(\x03R\x13yesterdayBigWinDraw\x124\n" +
	"\x15memberTodayBigWinDraw\x18\x10 \x01(\x03R\x15memberTodayBigWinDraw\x12<\n" +
	"\x19memberYesterdayBigWinDraw\x18\x11 \x01(\x03R\x19memberYesterdayBigWinDraw\x12.\n" +
	"\x12todayProvideRebate\x18\x12 \x01(\x03R\x12todayProvideRebate\x126\n" +
	"\x16yesterdayProvideRebate\x18\x13 \x01(\x03R\x16yesterdayProvideRebate\x12 \n" +
	"\vtodayRebate\x18\x14 \x01(\x03R\vtodayRebate\x12(\n" +
	"\x0fyesterdayRebate\x18\x15 \x01(\x03R\x0fyesterdayRebate\x12 \n" +
	"\vtotalRebate\x18\x16 \x01(\x03R\vtotalRebate\x12\x1a\n" +
	"\btodayWin\x18\x17 \x01(\x03R\btodayWin\x12\"\n" +
	"\fyesterdayWin\x18\x18 \x01(\x03R\fyesterdayWin\x12\"\n" +
	"\fprohibitGame\x18\x19 \x01(\x03R\fprohibitGame\x12\x1a\n" +
	"\bjoinTime\x18\x1a \x01(\x03R\bjoinTime2e\n" +
	"\vUserService\x12.\n" +
	"\bRegister\x12\x0f.RegisterParams\x1a\x11.RegisterResponse\x12&\n" +
	"\rFindUserByUid\x12\v.UserParams\x1a\b.UserDTOB\fZ\n" +
	"user/pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*RegisterParams)(nil),   // 0: RegisterParams
	(*RegisterResponse)(nil), // 1: RegisterResponse
	(*UserParams)(nil),       // 2: UserParams
	(*UserDTO)(nil),          // 3: UserDTO
	(*InviteMsg)(nil),        // 4: InviteMsg
	(*UnionInfo)(nil),        // 5: UnionInfo
}
var file_user_proto_depIdxs = []int32{
	4, // 0: UserDTO.inviteMsg:type_name -> InviteMsg
	0, // 1: UserService.Register:input_type -> RegisterParams
	2, // 2: UserService.FindUserByUid:input_type -> UserParams
	1, // 3: UserService.Register:output_type -> RegisterResponse
	3, // 4: UserService.FindUserByUid:output_type -> UserDTO
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
